export const RECEIVE_MORE_TWEETS = 'RECEIVE_MORE_TWEETS';
export const REQUEST_MORE_TWEETS_ERROR = 'REQUEST_MORE_TWEETS_ERROR';
export const REQUEST_SEARCH_TWEETS = 'REQUEST_SEARCH_TWEETS';
export const REQUEST_SEARCH_TWEETS_ERROR = 'REQUEST_SEARCH_TWEETS_ERROR';
export const RECEIVE_SEARCH_TWEETS = 'RECEIVE_SEARCH_TWEETS';
